# pubspec.yaml
#
name: restiview
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.3+42

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_database: ^12.1.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  geolocator: ^14.0.1
  http: ^1.1.0
  url_launcher: ^6.2.5
  diacritic: ^0.1.3
  package_info_plus: ^9.0.0
  flutter_secure_storage: ^10.0.0
  # added for image processing and temp file naming
  image: ^4.0.17
  uuid: ^4.0.0

  # Added for reverse geocoding (lat/lng to country)
  geocoding: ^4.0.0

  disk_space_2: ^1.0.11
  shared_preferences: ^2.2.2

  gal: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  googleapis_auth: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/restiview_icon_V4_yg.png

  fonts:
    - family: Literata
      fonts:
        - asset: fonts/Literata-Regular.ttf
        - asset: fonts/Literata-Italic.ttf
          style: italic
        - asset: fonts/Literata-Medium.ttf
          weight: 500
        - asset: fonts/Literata-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Literata-SemiBold.ttf
          weight: 600
        - asset: fonts/Literata-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Literata-Bold.ttf
          weight: 700
        - asset: fonts/Literata-BoldItalic.ttf
          weight: 700
          style: italic
    