// System-level constants for Restiview.
// These values are fixed and only modifiable by the program owner.
//

const String googlePlacesApiKey = 'AIzaSyAnUAcuBG7xvHR28IDPMFpyy8pKjHWeR0U';


const List<Map<String, String>> systemCountries = [
  {'code': 'US', 'name': 'USA', 'curr': 'US\$'},
  {'code': 'GB', 'name': 'United Kingdom', 'curr': '£'},
  {'code': 'FR', 'name': 'France', 'curr': '€'},
  {'code': 'DE', 'name': 'Germany', 'curr': '€'},
  {'code': 'IT', 'name': 'Italy', 'curr': '€'},
  {'code': 'ES', 'name': 'Spain', 'curr': '€'},
  {'code': 'CA', 'name': 'Canada', 'curr': 'C\$'},
  {'code': 'AU', 'name': 'Australia', 'curr': 'A\$'},
  {'code': 'BR', 'name': 'Brazil', 'curr': 'R\$'},
  {'code': 'JP', 'name': 'Japan', 'curr': '¥'},
  {'code': 'CN', 'name': 'China', 'curr': '¥'},
  {'code': 'IN', 'name': 'India', 'curr': '₹'},
  {'code': 'MX', 'name': 'Mexico', 'curr': 'MX\$'},
  {'code': 'KR', 'name': 'South Korea', 'curr': '₩'},
  {'code': 'TH', 'name': 'Thailand', 'curr': '฿'},
  {'code': 'NL', 'name': 'Netherlands', 'curr': '€'},
  {'code': 'CH', 'name': 'Switzerland', 'curr': 'CHF'},
  {'code': 'SE', 'name': 'Sweden', 'curr': 'kr'},
  {'code': 'ZA', 'name': 'South Africa', 'curr': 'R'},
  {'code': 'AR', 'name': 'Argentina', 'curr': 'ARS'},
];

// Utility methods
List<String> getSystemCountryNames() {
  return systemCountries.map((entry) => entry['name']!).toList();
}

String getCountryNameFromCode(String code) {
  return systemCountries.firstWhere(
    (entry) => entry['code'] == code,
    orElse: () => {'name': systemCountries.first['name']!},
  )['name']!;
}

String getCurrencyForCountry(String countryName) {
  final match = systemCountries.firstWhere(
    (c) => c['name'] == countryName,
    orElse: () => {'curr': '\$'},
  );
  return match['curr']!;
}


const List<String> goodForTags = [
  'Healthy',
  'Authentic',
  'A Date',
  'Great Wine/Beer',
  'Cozy',
  'Waterfront',
  'Sunday Lunch',
  'Happy Hour',
  'Vegan',
  'Business Meals',
  'Vegetarian',
  'Creative Cuisine',
  'Anniversaries',
  'Scenic View',
  'Special Occasion',
  'Organic',
];

const List<String> michelinLevels = [
  'None',
  '1 Star',
  '2 Stars',
  '3 Stars',
];

const List<String> ratingLabels = [
  'Food',
  'Service',
  'Ambiance',
  'Drinks',
  'Value for Money',
];

const List<String> systemCuisines = [
  'American',
  'Brazilian',
  'Chinese',
  'French',
  'Fusion',
  'Indian',
  'Italian',
  'Japanese',
  'Korean',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Pub Food',
  'Spanish',
  'Thai',
  'Vietnamese',
];

const List<String> systemOccasions = [
  'Anniversary',
  'Birthday',
  'Breakfast',
  'Business Meeting',
  'Casual Lunch',
  'Family Gathering',
  'Holiday Celebration',
  'Lunch',
  'Nothing Special',
  'Romantic Dinner',
  'Solo Dining',
  'Special Event',
];

const Map<String, List<String>> systemCitiesByCountry = {
  'USA': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
  'United Kingdom': ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Glasgow', 'Edinburgh', 'Bristol', 'Sheffield', 'Nottingham'],
  'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Leipzig', 'Bremen'],
  'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Florence', 'Bologna', 'Venice', 'Verona'],
  'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Bilbao', 'Alicante'],
  'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City', 'Hamilton', 'Victoria'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Gold Coast', 'Hobart', 'Darwin', 'Newcastle'],
  'Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
  'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Hiroshima', 'Sendai'],
  'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi’an', 'Nanjing', 'Tianjin'],
  'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Surat'],
  'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Zapopan', 'Ciudad Juárez', 'Mérida', 'San Luis Potosí'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Goyang'],
  'Thailand': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Khon Kaen', 'Hat Yai', 'Nakhon Ratchasima', 'Udon Thani', 'Surat Thani', 'Rayong'],
  'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],
  'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Lucerne', 'St. Gallen', 'Lugano', 'Thun', 'Winterthur'],
  'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Polokwane', 'Nelspruit', 'Kimberley'],
  'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
};
const List<String> allCountries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];